language: java
before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - wget -N http://chromedriver.storage.googleapis.com/2.11/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - sudo mv -f chromedriver /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
  # Install base Android SDK and components
  - export LICENSES="android-sdk-license-c81a61d9|android-sdk-license-ed0d0a5b|android-sdk-license-5be876d5|mips-android-sysimage-license-15de68cc|intel-android-sysimage-license-1ea702d1"
  - export COMPONENTS=android-19,android-20,android-21,android-22,android-23,sys-img-armeabi-v7a-android-19,sys-img-armeabi-v7a-android-21,sys-img-armeabi-v7a-android-22,sys-img-armeabi-v7a-android-23,extra-android-support,addon-google_apis-google-19,google-apis-19,addon-google_apis-google-20,google-apis-20,addon-google_apis-google-21,google-apis-21,addon-google_apis-google-22,google-apis-22,addon-google_apis-google-23,google-apis-23,extra-google-google_play_services,extra-google-gcm,build-tools-19.1.0,build-tools-20.0.1,build-tools-21.0.1,build-tools-22.0.5,build-tools-23.0.2,extra-google-m2repository,extra-android-m2repository
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS --accept=$LICENSES
  - source ~/.android-sdk-installer/env
  - android list targets
  # Create and start emulator
  - echo no | android create avd --force -n android-23 -t android-23 --abi armeabi-v7a
  -Â emulator -avd android-23 &
  - adb wait-for-device
  - adb shell input keyevent 82 &
  # Install appium
  - sudo npm install -g appium --chromedriver_version="2.16"
  - appium &
  - sudo apt-get update
  - sudo apt-get install unzip
  - sudo apt-get install google-chrome-stable
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: gradle clean test integrationTests browserTests

cache:
  directories:
  - apt
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/tools
